## Trying To Import Libraries

In [49]:
import numpy as np

In [50]:
print(np.__version__)

1.14.0


### Range and Converting to List

In [51]:
listOne = list(range(1,10,1))

In [52]:
print(listOne)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


### Conversion to array

In [53]:
arrayFromListOne = np.array(listOne)

In [54]:
print(arrayFromListOne)

[1 2 3 4 5 6 7 8 9]


In [55]:
arrayMultiplied = arrayFromListOne * 10

In [56]:
print(arrayMultiplied)

[10 20 30 40 50 60 70 80 90]


### Creating Array using NumPy

In [57]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [58]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])